project:
  type: website

website:
  title: "Scribble Scribble Draw"
  site-url: https://avocatokitty.github.io/my-kawaii/
  description: "How to Scribble :-)"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
        rel: me
      - icon: github
        href: https://github.com/avocatoKitty
format:
  html:
    theme: sketchy
    css: styles.css



